### ISSUE TITLE
nexus 3.1.0 config file location changed

### ISSUE THREAD

**Issue by iurii-polishchuk** [dhoer/chef-nexus3#17]
Hi!

The configuration file location was changed for nexus 3.1.0 from $install-dir/etc/org.sonatype.nexus.cfg to $data-dir/etc/nexus.properties. (https://books.sonatype.com/nexus-book/3.1/reference/install.html#config-http-port)

Could you kindly fix that?

Thank you!

**Comment by dhoer** [comment]
If you can submit a PR for this, that would be great.  Im working on other things and don't know when I will have time to address this.
