### ISSUE TITLE
node['nexus3']['path'] is incorrect

### ISSUE THREAD

**Issue by steven-turner** [dhoer/chef-nexus3#20]
node['nexus3']['path'] has default value of "/opt" on linux, rather than the documented value of "/opt/sonatype". This causes problems on both install (chown -R nexus:nexus /opt) and on uninstall (rm -fr /opt).

**Comment by dhoer** [comment]
This must have changed in 3.2 and the tests missed it. Where is this documented, so I can update home and data attributes?  If you want to submit a PR for this, that would be welcomed as well.
```
default['nexus3']['home'] = "#{node['nexus3']['path']}/nexus3"
default['nexus3']['data'] = "#{node['nexus3']['path']}/sonatype-work/nexus3"
```

**Comment by steven-turner** [comment]
[README.md](https://github.com/dhoer/chef-nexus3/blob/master/README.md) documents the default value of node['nexus3']['path'] to be "Default Linux: /opt/sonatype Windows: #{ENV['SYSTEMDRIVE']}/sonatype." However, the actual default value defined in [attributes/default.rb](https://github.com/dhoer/chef-nexus3/blob/master/attributes/default.rb) is

    default['nexus3']['path'] = '/opt'

This was changed in the[ latest commit](https://github.com/dhoer/chef-nexus3/commit/105d56fae4b9e62b9ca0d52f277ed238788f5e6c#diff-25e5d4a4446ae12a0d6f1162b6160375), from prior value of '/opt/sonatype'

The needed fix is to revert the value of this setting. The work-around is to just override the default setting.

**Comment by dhoer** [comment]
When migrating from 3.0 to 3.1, nexus changed the install and configuration which wasn't backwards compatible.  I bumped the major version from 1 to 2 to comply with semver.  The current install follows the documention referenced here: https://books.sonatype.com/nexus-book/reference3/install.html#installation-archive.  

I guess the readme attributes were not updated to reflect this.  I will update the readme to reflect the change.  Sorry about the confusion.

I would just update the attribute to be `node.override['nexus3']['path'] = '/opt/sonatype'` to get to what you are wanting.

**Comment by dhoer** [comment]
This cookbook has been adopted: https://github.com/criteo-cookbooks/nexus3
