### ISSUE TITLE
Add another variable to nexus.properties.erb to configure nexus-args

### ISSUE THREAD

**Issue by Lasering** [dhoer/chef-nexus3#22]
For people like me that would like to access Nexus exclusively via HTTPS adding an extra variable to the nexus.properties.erb temple in order to configure nexus-args would be very handy.

I can make a pull request if that would facilitate it.

**Comment by dhoer** [comment]
Sure, I don't see any problem with that.  Please make sure unit tests pass and to update readme attributes section. Thanks in advance.

**Comment by Lasering** [comment]
Do you think it is possible to release a new version in supermarket with the new changes?

**Comment by dhoer** [comment]
Done
