### ISSUE TITLE
nexus3_api does not work if script_source is a groovy file

### ISSUE THREAD

**Issue by Lasering** [dhoer/chef-nexus3#24]
Currently the nexus3_api [assumes](https://github.com/dhoer/chef-nexus3/blob/master/providers/api.rb#L35) the `script_source` will be a json file.

Using a groovy file should also work, as is it way more simple to work with.

**Comment by dhoer** [comment]
A PR on making this happen would be most welcome.

**Comment by dhoer** [comment]
This cookbook has been adopted: https://github.com/criteo-cookbooks/nexus3
