### ISSUE TITLE
Deprecated features used - name collisions

### ISSUE THREAD

**Issue by cnaude** [dhoer/chef-nexus3#27]
Looks like there are a couple of name collisions.

    Property `ignore_failure` of resource `nexus3_api` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. at 1 location:
    - /tmp/kitchen/cache/cookbooks/nexus3/resources/api.rb:14:in `class_from_file'
    Property `sensitive` of resource `nexus3_api` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. at 1 location:
    - /tmp/kitchen/cache/cookbooks/nexus3/resources/api.rb:17:in `class_from_file'

**Comment by dhoer** [comment]
@cnaude Criteo now maintains this cookbook: https://github.com/criteo-cookbooks/nexus3

**Comment by cnaude** [comment]
Okay thanks. The source and issues links on the supermarket page still link to this github.

**Comment by dhoer** [comment]
Thanks for letting me know.  Criteo has now fixed the links.
